### PR TITLE
PirateShip

### PR DESCRIPTION
**Pull request by EmperorNumerius**

### CODE REVIEW

**Comment by espcaa** [comment]
Hey can you rename it to only emperor numerous.png because I plan to use the filenames for the vote 😓

**Comment by EmperorNumerius** [comment]
@Spectralo can you use this image instead i missed 3 pixels on the submission one and its named numerius.png
Numerius

**Comment by espcaa** [comment]
Uhm I can't rn

**Comment by espcaa** [comment]
Just git pull to merge then change the file and recommit

**Pull request closed without merging**
